Add documentation for PKCS #11 with IBM CEX
containers/ocicrypt pull request #55
Opened 2021-08-23 13:33 UTC by Jakob-Naucke

Documentation for backing OCIcrypt with PKCS #11 and SoftHSM2 is already
available. It is also possible to do this with an IBM CryptoExpress HSM,
but there are some specifics to know. Add documentation for this.

Signed-off-by: Jakob Naucke <jakob.naucke@ibm.com>

2021-08-23 19:06 UTC, stefanberger commented
@Jakob-Naucke Great! I had used the IBM CEX for experiments previously and it helped shape the code to what it is now. I am currently away but I'll have a look at your write-up once I am back. Thanks!

2021-08-23 19:29 UTC, lumjjb reviewed
Awesome - thanks @Jakob-Naucke , made a couple suggested nits. And in addition, suggested adding a line to just spell out that this is not an endorsement of any particular choice.

2021-08-23 19:29 UTC, lumjjb commented on docs/cex-ep11.md
> +Some things to watch out for:
```suggestion
### Some things to watch out for:
```

2021-08-23 19:29 UTC, lumjjb commented on docs/cex-ep11.md
> +
```suggestion

Note: This is a tutorial on using IBM CryptoExpress as an example of use of the ocicrypt library. This is not an endorsement or recommendation to use IBM CryptoExpress.
```

2021-08-25 10:28 UTC, Jakob-Naucke commented
added a paragraph separator

2021-09-16 19:05 UTC, lumjjb commented
@stefanberger do you have a chance to look at this? Am good from my side, but this is your area of specialty, so will defer to you.

2021-09-16 19:27 UTC, stefanberger requested changes

2021-09-16 19:27 UTC, stefanberger commented on docs/cex-ep11.md
> +Instead, it is also possible to use an [IBM CryptoExpress HSM](https://www.ibm.com/security/cryptocards) in Enterprise PKCS #11 (EP11) mode, available for IBM Z and x64, together with the [openCrypto
Instead->However

2021-09-16 19:29 UTC, stefanberger commented
Ah, I had forgotten about this PR. Apart from that one change I requested it looks good to me.

2021-09-17 12:34 UTC, stefanberger approved these changes

2021-09-17 12:35 UTC, stefanberger commented
LGTM.

2021-09-17 13:09 UTC, merged