remove github.com/pkg/errors
containers/ocicrypt pull request #78
Opened 2023-01-11 03:30 UTC by Iceber

[pkg/errors](https://github.com/pkg/errors) has been archived and we use `fmt.Errorf` to replace `errors.Wrap`/`errors.Wrapf`

2023-01-15 12:39 UTC, rhatdan commented
LGTM

2023-01-15 13:08 UTC, lumjjb requested changes
1 minor typo, else LGTM!

2023-01-15 13:08 UTC, lumjjb commented on utils/ioutils.go
> +		return nil, fmt.Errorf("Error while running command: %s. stderr: %s: %s", cmdName, stderr.String(), err)
```suggestion
		return nil, fmt.Errorf("Error while running command: %s. stderr: %s: %w", cmdName, stderr.String(), err)
```

2023-01-16 00:07 UTC, stefanberger commented
LGTM

2023-01-16 07:40 UTC, Iceber commented on utils/ioutils.go
> +		return nil, fmt.Errorf("Error while running command: %s. stderr: %s: %s", cmdName, stderr.String(), err)
Thanks, updated

2023-01-17 22:23 UTC, merged